import esbuild from "esbuild";
import process from "process";
// Node's own built-in module list (replaces the `builtin-modules` package, which
// eslint-plugin-obsidianmd's depend/ban-dependencies flags). Externalizing every builtin
// is what lets the vendored EngineHost reach `child_process`/`fs`/`https` through
// `window.require` without esbuild resolving a Node core module into the bundle.
import { builtinModules as builtins } from "node:module";

const banner = `/*
This file is auto-generated by esbuild. Edit the source in src/ instead.
Standing Questions
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  // es2020, not es2018: the vendored shared/hash.mjs uses BigInt literals (FNV-1a-64),
  // which esbuild refuses to lower below es2020.
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  platform: "browser",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
