/** GENERATED DATA — regenerated by scripts/pin-engine.mjs. See engineRelease.mjs. */

import type { EngineTarget } from "./installPlan.mjs";

export const PLACEHOLDER_SHA256: string;
/** False until pin-engine.mjs has run against a published release. EngineHost refuses to download while false. */
export const ENGINE_RELEASE_PINNED: boolean;
export const ENGINE_VERSION: string;
export const ENGINE_RELEASE_TAG: string;
export const ENGINE_MODEL: string;
export const ENGINE_DIM: number;
export const ENGINE_ASSET_SHA256: Readonly<Record<EngineTarget, string>>;
export function isPlaceholderSha256(sha256: string): boolean;
